name: Build for iOS

on:
    workflow_dispatch:
    push:

jobs:
    build_cpython:
        name: Build CPython
        concurrency:
            group: ${{ github.ref }}
            cancel-in-progress: true

        runs-on: macos-12
        steps:
            - uses: actions/checkout@v3
              #with:
                  #submodules: recursive

            # BUILDING

            - run: sh ./downloadFrameworks.sh

            # We need to build for macOS before we can build for iOS
            - run: sh ./buildForOSX.sh

            - run: sh ./buildForiOS.sh

            # LOGGING / DEBUGGING

            # Failure only steps should go first so if another debugging step fails it doesn't trigger a failure only step

            - name: Run tree if the job failed
              run: brew install tree && tree
              if: always() && job.status == 'failure'

            - run: cat ./configure_osx.log
              if: always()
            - run: cat ./make_osx.log
              if: always()
            - run: cat ./make_install_osx.log
              if: always()

            - run: cat ./configure_ios.log
              if: always()
            - run: cat ./make_ios.log
              if: always()
